# Generated by Django 3.2.20 on 2024-01-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231215_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jobs',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
